version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: predictedge-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data/uploads:/backend/app/data/uploads
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: predictedge-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1=value
  